"""Add project_name to CodeSubmission model

Revision ID: 4da496ea0231
Revises: e643fb925df2
Create Date: 2025-06-27 18:10:27.220816

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4da496ea0231"
down_revision: Union[str, None] = "e643fb925df2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "code_submissions",
        sa.Column(
            "project_name",
            sa.String(),
            nullable=False,
            server_default="Untitled Project",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("code_submissions", "project_name")
    # ### end Alembic commands ###
