"""add original_snippet with default

Revision ID: 5e9502cc1126
Revises: 68d9b6d5d8a6
Create Date: 2025-07-01 20:47:03.685899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9502cc1126'
down_revision: Union[str, None] = '68d9b6d5d8a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_submissions', sa.Column('workflow_mode', sa.String(), nullable=True, comment="The selected workflow mode, e.g., 'audit' or 'audit_and_remediate'."))
    op.add_column('fix_suggestions', sa.Column('original_snippet', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fix_suggestions', 'original_snippet')
    op.drop_column('code_submissions', 'workflow_mode')
    # ### end Alembic commands ###
