"""Add framework, agent, and prompt template models

Revision ID: 78f1c84a7f2d
Revises: 25281731aab4
Create Date: 2025-07-10 19:30:24.721556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f1c84a7f2d'
down_revision: Union[str, None] = '25281731aab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('domain_query', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.create_table('frameworks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frameworks_name'), 'frameworks', ['name'], unique=True)
    op.create_table('framework_agent_mappings',
    sa.Column('framework_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.PrimaryKeyConstraint('framework_id', 'agent_id')
    )
    op.add_column('prompt_templates', sa.Column('template_type', sa.String(length=50), server_default='QUICK_AUDIT', nullable=False))
    op.create_index(op.f('ix_prompt_templates_template_type'), 'prompt_templates', ['template_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_templates_template_type'), table_name='prompt_templates')
    op.drop_column('prompt_templates', 'template_type')
    op.drop_table('framework_agent_mappings')
    op.drop_index(op.f('ix_frameworks_name'), table_name='frameworks')
    op.drop_table('frameworks')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
