"""Add estimated_cost to CodeSubmission

Revision ID: c2f73670e1ac
Revises: 7f2f0b11c54f
Create Date: 2025-06-21 18:08:20.642109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c2f73670e1ac"
down_revision: Union[str, None] = "7f2f0b11c54f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "code_submissions",
        sa.Column(
            "estimated_cost",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Stores the estimated cost breakdown for the analysis.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("code_submissions", "estimated_cost")
    # ### end Alembic commands ###
