"""add file_path to llm_interaction table

Revision ID: d5367d473747
Revises: cf682e096e83
Create Date: 2025-07-10 13:35:16.053128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5367d473747'
down_revision: Union[str, None] = 'cf682e096e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_interactions', sa.Column('file_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_interactions', 'file_path')
    # ### end Alembic commands ###
