"""Add dynamic pricing and tokenizer to LLMConfig

Revision ID: 7f2f0b11c54f
Revises: bfc3d81cfcc9
Create Date: 2025-06-21 17:31:50.195001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2f0b11c54f'
down_revision: Union[str, None] = 'bfc3d81cfcc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configurations', sa.Column('tokenizer_encoding', sa.String(length=100), server_default='cl100k_base', nullable=False, comment="The name of the tiktoken tokenizer, e.g., 'cl100k_base' or 'o200k_base'."))
    op.add_column('llm_configurations', sa.Column('input_cost_per_million', sa.Float(), server_default='0.0', nullable=False, comment='Cost per 1 million input tokens in USD.'))
    op.add_column('llm_configurations', sa.Column('output_cost_per_million', sa.Float(), server_default='0.0', nullable=False, comment='Cost per 1 million output tokens in USD.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configurations', 'output_cost_per_million')
    op.drop_column('llm_configurations', 'input_cost_per_million')
    op.drop_column('llm_configurations', 'tokenizer_encoding')
    # ### end Alembic commands ###
