"""Add report fields to CodeSubmission

Revision ID: bbe5b1b68796
Revises: c2f73670e1ac
Create Date: 2025-06-21 22:54:58.520162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbe5b1b68796'
down_revision: Union[str, None] = 'c2f73670e1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_submissions', sa.Column('impact_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Stores the JSON output of the AI-generated impact report.'))
    op.add_column('code_submissions', sa.Column('sarif_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Stores the generated SARIF report as a JSON object.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_submissions', 'sarif_report')
    op.drop_column('code_submissions', 'impact_report')
    # ### end Alembic commands ###
