"""add cwe details, owasp mapping, and cvss fields to findings

Revision ID: e6ba315b88c4
Revises: 70ac1d466fe5
Create Date: 2025-07-19 15:41:12.211904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ba315b88c4'
down_revision: Union[str, None] = '70ac1d466fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cwe_details',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('abstraction', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rag_document_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cwe_owasp_mappings',
    sa.Column('cwe_id', sa.String(length=20), nullable=False),
    sa.Column('owasp_category_id', sa.String(length=10), nullable=False),
    sa.Column('owasp_category_name', sa.String(length=255), nullable=False),
    sa.Column('owasp_rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cwe_id'], ['cwe_details.id'], ),
    sa.PrimaryKeyConstraint('cwe_id')
    )
    op.add_column('findings', sa.Column('cvss_score', sa.DECIMAL(precision=3, scale=1), nullable=True))
    op.add_column('findings', sa.Column('cvss_vector', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'cvss_vector')
    op.drop_column('findings', 'cvss_score')
    op.drop_table('cwe_owasp_mappings')
    op.drop_table('cwe_details')
    # ### end Alembic commands ###
