"""Add rag_preprocessing_jobs table

Revision ID: feb3ea9929d5
Revises: 55bce92a6c64
Create Date: 2025-07-17 00:24:19.281313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'feb3ea9929d5'
down_revision: Union[str, None] = '55bce92a6c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_preprocessing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('framework_name', sa.String(length=255), nullable=False),
    sa.Column('llm_config_id', sa.UUID(), nullable=False),
    sa.Column('original_file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('estimated_cost', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_cost', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('processed_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['llm_config_id'], ['llm_configurations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_preprocessing_jobs_original_file_hash'), 'rag_preprocessing_jobs', ['original_file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_preprocessing_jobs_original_file_hash'), table_name='rag_preprocessing_jobs')
    op.drop_table('rag_preprocessing_jobs')
    # ### end Alembic commands ###
