"""Add RepositoryMapCache table

Revision ID: bfc3d81cfcc9
Revises: 02f5bf6d1f79
Create Date: 2025-06-21 14:50:08.085192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bfc3d81cfcc9"
down_revision: Union[str, None] = "02f5bf6d1f79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository_map_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codebase_hash", sa.String(), nullable=False),
        sa.Column(
            "repository_map", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repository_map_cache_codebase_hash"),
        "repository_map_cache",
        ["codebase_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_repository_map_cache_id"), "repository_map_cache", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repository_map_cache_id"), table_name="repository_map_cache")
    op.drop_index(
        op.f("ix_repository_map_cache_codebase_hash"), table_name="repository_map_cache"
    )
    op.drop_table("repository_map_cache")
    # ### end Alembic commands ###
