"""Add llm_config_id to chat_sessions and tokenizer to llm_configs

Revision ID: 91cbba3e877d
Revises: 78f1c84a7f2d
Create Date: 2025-07-11 03:09:19.116769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91cbba3e877d'
down_revision: Union[str, None] = '78f1c84a7f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('cost', sa.DECIMAL(precision=10, scale=8), nullable=True))
    op.add_column('chat_sessions', sa.Column('llm_config_id', sa.UUID(), nullable=True))
    op.add_column('chat_sessions', sa.Column('frameworks', sa.ARRAY(sa.String()), nullable=True))
    op.create_foreign_key('fk_chat_sessions_llm_config_id_llm_configurations', 'chat_sessions', 'llm_configurations', ['llm_config_id'], ['id'])
    op.add_column('llm_configurations', sa.Column('tokenizer_encoding', sa.String(length=100), server_default='cl100k_base', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configurations', 'tokenizer_encoding')
    op.drop_constraint('fk_chat_sessions_llm_config_id_llm_configurations', 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'frameworks')
    op.drop_column('chat_sessions', 'llm_config_id')
    op.drop_column('chat_messages', 'cost')
    # ### end Alembic commands ###