"""Add is_applied_in_remediation to findings table

Revision ID: 13e96dcb0fcd
Revises: e6ba315b88c4
Create Date: 2025-07-19 21:18:34.354096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e96dcb0fcd'
down_revision: Union[str, None] = 'e6ba315b88c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('is_applied_in_remediation', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'is_applied_in_remediation')
    # ### end Alembic commands ###
