"""Add analysis artifact columns to scans

Revision ID: 55bce92a6c64
Revises: 8ccd680ec857
Create Date: 2025-07-15 22:51:42.854160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55bce92a6c64'
down_revision: Union[str, None] = '8ccd680ec857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('repository_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scans', sa.Column('dependency_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('scans', sa.Column('context_bundles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'context_bundles')
    op.drop_column('scans', 'dependency_graph')
    op.drop_column('scans', 'repository_map')
    # ### end Alembic commands ###
