"""add confidence to finding table

Revision ID: fdd0456dc96e
Revises: d5367d473747
Create Date: 2025-07-10 14:03:11.993236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdd0456dc96e'
down_revision: Union[str, None] = 'd5367d473747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('confidence', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'confidence')
    # ### end Alembic commands ###
