"""Add raw_content to rag_preprocessing_jobs

Revision ID: 9b83bc4f8fb9
Revises: 4f2e49c268be
Create Date: 2025-07-17 00:42:02.021530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b83bc4f8fb9'
down_revision: Union[str, None] = '4f2e49c268be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_preprocessing_jobs', sa.Column('raw_content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_preprocessing_jobs', 'raw_content')
    # ### end Alembic commands ###
