"""Add tokenizer to llm configs

Revision ID: 465439f4d074
Revises: becc822c0470
Create Date: 2025-07-20 19:01:57.272962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465439f4d074'
down_revision: Union[str, None] = 'becc822c0470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configurations', sa.Column('tokenizer', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configurations', 'tokenizer')
    # ### end Alembic commands ###
