"""Removed Tokenizer Encoding Field

Revision ID: 70ac1d466fe5
Revises: 9b83bc4f8fb9
Create Date: 2025-07-17 11:33:11.516717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ac1d466fe5'
down_revision: Union[str, None] = '9b83bc4f8fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configurations', 'tokenizer_encoding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configurations', sa.Column('tokenizer_encoding', sa.VARCHAR(length=100), server_default=sa.text("'cl100k_base'::character varying"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
