"""add_interaction_context_to_llm_interactions_if_needed

Revision ID: 72fc0c97da24
Revises: 78e625208988
Create Date: 2025-05-29 11:15:54.711714

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "72fc0c97da24"
down_revision: Union[str, None] = "78e625208988"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
