"""add users table and link to submissions

Revision ID: 78e625208988
Revises: ccccd7e489e0
Create Date: 2024-05-20 00:09:59.083788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Corrected import for the GUID type
from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision: str = "78e625208988"
down_revision: Union[str, None] = "ccccd7e489e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.add_column("submissions", sa.Column("user_id", GUID(), nullable=True))
    # Provide a specific name for the foreign key constraint
    op.create_foreign_key(
        "fk_submissions_user_id_user", "submissions", "user", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use the specific name to drop the foreign key constraint
    op.drop_constraint("fk_submissions_user_id_user", "submissions", type_="foreignkey")
    op.drop_column("submissions", "user_id")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
