"""create_tables_with_autogenerate

Revision ID: ccccd7e489e0
Revises: 
Create Date: 2025-05-27 12:35:45.502668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccccd7e489e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_language', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('selected_frameworks', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_submissions_id'), 'code_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_code_submissions_primary_language'), 'code_submissions', ['primary_language'], unique=False)
    op.create_table('security_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('query_content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'ACTIVE', 'REJECTED', 'INACTIVE', name='query_status_enum'), nullable=False),
    sa.Column('cwe_id', sa.String(), nullable=True),
    sa.Column('asvs_category', sa.String(), nullable=True),
    sa.Column('suggested_by_agent_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_name')
    )
    op.create_index(op.f('ix_security_queries_language'), 'security_queries', ['language'], unique=False)
    op.create_index(op.f('ix_security_queries_status'), 'security_queries', ['status'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('report_content', sa.JSON(), nullable=True),
    sa.Column('original_code_snapshot', sa.JSON(), nullable=True),
    sa.Column('fixed_code_snapshot', sa.JSON(), nullable=True),
    sa.Column('sarif_report', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['code_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_status'), 'analysis_results', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_results_submission_id'), 'analysis_results', ['submission_id'], unique=True)
    op.create_table('llm_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prompt_title', sa.String(length=255), nullable=True),
    sa.Column('input_prompt', sa.Text(), nullable=False),
    sa.Column('output_response', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('interaction_context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['code_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_interactions_agent_name'), 'llm_interactions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_llm_interactions_id'), 'llm_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_llm_interactions_status'), 'llm_interactions', ['status'], unique=False)
    op.create_index(op.f('ix_llm_interactions_submission_id'), 'llm_interactions', ['submission_id'], unique=False)
    op.create_table('submitted_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('detected_language', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['code_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submitted_files_detected_language'), 'submitted_files', ['detected_language'], unique=False)
    op.create_index(op.f('ix_submitted_files_submission_id'), 'submitted_files', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submitted_files_submission_id'), table_name='submitted_files')
    op.drop_index(op.f('ix_submitted_files_detected_language'), table_name='submitted_files')
    op.drop_table('submitted_files')
    op.drop_index(op.f('ix_llm_interactions_submission_id'), table_name='llm_interactions')
    op.drop_index(op.f('ix_llm_interactions_status'), table_name='llm_interactions')
    op.drop_index(op.f('ix_llm_interactions_id'), table_name='llm_interactions')
    op.drop_index(op.f('ix_llm_interactions_agent_name'), table_name='llm_interactions')
    op.drop_table('llm_interactions')
    op.drop_index(op.f('ix_analysis_results_submission_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_status'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_security_queries_status'), table_name='security_queries')
    op.drop_index(op.f('ix_security_queries_language'), table_name='security_queries')
    op.drop_table('security_queries')
    op.drop_index(op.f('ix_code_submissions_primary_language'), table_name='code_submissions')
    op.drop_index(op.f('ix_code_submissions_id'), table_name='code_submissions')
    op.drop_table('code_submissions')
    # ### end Alembic commands ###
